/**
 * Sprint Review Generator - генерация отчёта о спринте
 *
 * Анализирует:
 * - Task queue (задачи, stories)
 * - Git commits
 * - Learnings из scratchpad.md
 */

import * as fs from 'fs/promises';
import { exec } from 'child_process';
import { promisify } from 'util';
import type { TaskQueue, Story } from './task-queue-types';
import { groupTasksByStory, getCommitsFromTasks, calculateTotalDuration } from './task-queue-types';

const execAsync = promisify(exec);

// ============================================================================
// Generate Sprint Review
// ============================================================================

/**
 * Генерировать Sprint Review markdown отчёт
 */
export async function generateSprintReview(queue: TaskQueue): Promise<string> {
  console.log('\n📝 Generating Sprint Review...\n');

  const stories = groupTasksByStory(queue.tasks);
  const completedStories = stories.filter(s => s.completed_tasks === s.total_tasks);
  const commits = getCommitsFromTasks(queue.tasks);
  const totalDuration = calculateTotalDuration(queue.tasks);

  // Читаем learnings из scratchpad
  const learnings = await readLearningsFromScratchpad();

  // Генерируем markdown
  const review = `# Sprint ${queue.sprint} Review

**Completed:** ${new Date().toISOString()}

## Summary

- **Sprint:** ${queue.sprint}
- **Stories:** ${completedStories.length}/${stories.length} completed
- **Tasks:** ${queue.summary.completed_tasks}/${queue.summary.total_tasks} done
- **Commits:** ${commits.length}
- **Duration:** ${Math.round(totalDuration / 60)} hours

## Stories Delivered

${renderStories(stories)}

## Git Commits

${commits.length > 0 ? renderCommits(commits) : '_No commits recorded_'}

## Blockers & Learnings

${learnings.length > 0 ? learnings.join('\n') : '_No learnings recorded_'}

---

_Generated by Ralph Loop Sprint Automation_
`;

  return review;
}

// ============================================================================
// Helpers
// ============================================================================

/**
 * Рендер stories в markdown
 */
function renderStories(stories: Story[]): string {
  return stories.map(story => {
    const status = story.completed_tasks === story.total_tasks ? '✅' : '⏳';
    const tasks = story.tasks.map(task => {
      const taskStatus = task.status === 'done' ? '✅' : '⏳';
      return `  - ${taskStatus} ${task.id}: ${task.title}`;
    }).join('\n');

    return `### ${status} ${story.story_id} (${story.completed_tasks}/${story.total_tasks} tasks)

${tasks}
`;
  }).join('\n');
}

/**
 * Рендер commits в markdown
 */
function renderCommits(commits: string[]): string {
  return commits.map(hash => `- \`${hash}\``).join('\n');
}

/**
 * Читать learnings из .bmad/scratchpad.md
 */
async function readLearningsFromScratchpad(): Promise<string[]> {
  try {
    const content = await fs.readFile('.bmad/scratchpad.md', 'utf-8');

    // Парсим секцию "learnings:"
    const learningsMatch = content.match(/learnings:\s*\n((?:  - .+\n?)+)/);
    if (learningsMatch) {
      const learningsText = learningsMatch[1];
      return learningsText.split('\n')
        .filter(line => line.trim().startsWith('- '))
        .map(line => line.trim());
    }

    return [];
  } catch (error) {
    return [];
  }
}
